spring:
  cloud:
    stream:
      bindings:
        output:
          destination: queue.created-account.messages
          binder: local-rabbit
      binders:
        local-rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: rabbitmq
                password: rabbitmq
                virtual-host: /
